name: Deploy Dockerhub

on:
  push:
    branches:
      - hello

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/checkout@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t precious002/devops-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push precious002/devops-app:latest

      - name: upload deploy script
        uses: actions/upload-artifact@v2
        with:
          name: deploy-script
          path: deploy.sh

      - name: Deploy to AWS EC2
        run: |
          scp -i ${{ secrets.AWS_SSH_KEY }} -o StrictHostKeyChecking=no deploy.sh ${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_INSTANCE_IP }}:/tmp/deploy.sh
          ssh -i ${{ secrets.AWS_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_INSTANCE_IP }} 'bash /tmp/deploy.sh'

